### ISSUE TITLE
Chilipepper Tinyg Settings 

### ISSUE THREAD

**Issue by jonc1980** [chilipeppr/tinyg#45]
I am rebuilding my CNC and need to change some settings on my TinyG. All that is returned when I click the Configure TinyG button is an "Edit in JSFiddle" link followed by a bullet with a link labeled "Result".  How do I resolve this?

**Comment by chilipeppr** [comment]
Try it now. Just fixed it.

**Comment by jonc1980** [comment]
Way past due house keeping on my part.  Sorry for not confirming but the issue was resolved.
