### ISSUE TITLE
Internal Server Error  - Chilipeppr/Tinyg not opening on web browser

### ISSUE THREAD

**Issue by GravityInc** [chilipeppr/tinyg#48]
Hi Guys,

Hope you all are safe and doing well....

Today i tried to launch chilipeppr/tinyg on my browser and it was loading a blank page.

When i inspect the webpage i see the below. Please can you suggest me a way to resolve it.

![image](https://user-images.githubusercontent.com/12138029/89378758-df6f2e00-d737-11ea-8f1b-b3f7717abdb0.png)

**Comment by chilipeppr** [comment]
Google shutdown anything below go 1.10 for app engineer and thus chilipeppr
needs recompiled, but the problem is they deprecated core libraries so
certain things need reimplemented from scratch.

**Comment by chilipeppr** [comment]
Ok. Fixed. Should be ok now.

Had to hard code all the popular workspaces to get this up and running quickly. The database model has to get rewritten this weekend, which is where the workspace boot scripts are stored. No logins work either, although there's very limited functionality that relies on that, so we should be fine now for everyone to be functioning again.

**Comment by GravityInc** [comment]
Thanks mate! really appreciate you effort and this application.

Was wondering if there is a way I can contribute to the code?

I will close this issue....
